input{
    # http 5044번 입력
    http{
        port => 5044
    }
}
filter{
    # Grok 을 사용하여 비정형 -> 반전형 으로 change
    if [log] =~ "ID=" {
        # 변환 처리 => {key:value}
        # %{패턴명:필드명:데이터타입} or %{패턴명:필드명}
        grok {
            match => { "log" => "\[%{TIMESTAMP_ISO8601:log_time}\] ID=%{DATA:device_id} \|   TEMP:%{NUMBER:temp:float} \|   HUMI:%{NUMBER:humi:float} \|   STAT:%{WORD:status}" }
        }
    }
}
output{
    # kafka 브로커에게 전송 (9092) 그럼 이후 -> 백터 -> KDF
    kafka {
        bootstrap_servers => "kafka:9092"
        topic_id => "factory-text-topic"
        codec => json
    }
    # 디버깅용 콘솔출력
    stdout {
        codec => rubydebug
    }

}